[package]
name = "solana-feature-gate-interface"
description = "Solana feature gate program interface."
documentation = "https://docs.rs/solana-feature-gate-interface"
version = "5.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = [
    "dep:bincode",
    "dep:solana-account",
    "dep:solana-account-info",
    "dep:solana-instruction",
    "dep:solana-system-interface",
    "serde",
    "solana-account/bincode",
    "solana-system-interface/bincode",
]
dev-context-only-utils = ["bincode", "wincode"]
serde = ["dep:serde", "dep:serde_derive"]
wincode = [
    "dep:solana-account",
    "dep:solana-account-info",
    "dep:solana-instruction",
    "dep:solana-system-interface",
    "dep:wincode",
    "solana-account/wincode",
    "solana-system-interface/wincode",
    "wincode/alloc",
]

[dependencies]
bincode = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-account = { workspace = true, optional = true }
solana-account-info = { workspace = true, optional = true }
solana-instruction = { workspace = true, optional = true }
solana-program-error = { workspace = true }
solana-pubkey = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-system-interface = { workspace = true, optional = true }
wincode = { workspace = true, optional = true }

[dev-dependencies]
bincode = { workspace = true }
solana-feature-gate-interface = { path = ".", features = ["dev-context-only-utils"] }
solana-pubkey = { workspace = true, features = ["std"] }
strum = { workspace = true }
strum_macros = { workspace = true }

[lints]
workspace = true
